# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ed
tagline:             'A Jekyll theme for minimal editions'
description:         'Min-ed, or simply Ed, is a [Jekyll](https://jekyllrb.com/) theme designed for textual editors based on [minimal computing principles](http://go-dh.github.io/mincomp/), and focused on legibility and flexibility.'
url:                 https://github.com/elotroalex/ed
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Alex Gil
  url:               https://twitter.com/elotroalex
  email:             colibri.alex@gmail.com

# Custom vars
version:             1.0.0
