# Built with Jekyll 2.5.3
#
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Footnote friendly markdown
markdown: kramdown

# Setup
title:               Ed
tagline:             'A Jekyll theme for minimal editions'
description:         'Ed is a Jekyll theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
url:                 https://github.com/elotroalex/ed
baseurl:             ''

# About/contact
author:
  name:              Alex Gil
  url:               https://twitter.com/elotroalex
  email:             colibri.alex@gmail.com

# Custom vars
version:             0.0.1
